#Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its  application.
Ans -

Min-Max scaling is a data normalization technique that rescales the values of each feature in a dataset to a range of 0 to 1. This is done by subtracting the minimum value of each feature from all of its values, and then dividing by the range of the feature.

Min-Max scaling is used in data preprocessing to ensure that all features have a similar scale. This is important for many machine learning algorithms, as they can be sensitive to the scale of the features. For example, an algorithm that uses Euclidean distance as a similarity measure will be more sensitive to features with larger values.

To illustrate the application of Min-Max scaling, consider the following dataset of house prices:
- Feature | Value
------- | --------
Sq. ft. | 1000
Bedrooms | 3
Bathrooms | 2
Price | \$500,000

The minimum value of the Sq. ft. feature is 1000, and the maximum value is 2000. The minimum value of the Price feature is $500,000, and the maximum value is $1,000,000.

To apply Min-Max scaling to this dataset, we would first subtract the minimum value of each feature from all of its values. This would give us the following:

Feature | Value
------- | --------
Sq. ft. | 0
Bedrooms | 2
Bathrooms | 1
Price | 0
We would then divide each value by the range of the feature. For the Sq. ft. feature, the range is 2000 - 1000 = 1000. So, we would divide each value in the Sq. ft. column by 1000. This would give us the following:

- Feature | Value
------- | --------
Sq. ft. | 0.1
Bedrooms | 2
Bathrooms | 1
Price | 0.5

After Min-Max scaling, all of the features in the dataset have a range of 0 to 1. This makes them more comparable to each other, and it can help to improve the performance of machine learning algorithms.

Here are some of the advantages of using Min-Max scaling:

It is simple to understand and implement.
It can be used with any type of data.
It does not make any assumptions about the distribution of the data.
Here are some of the disadvantages of using Min-Max scaling:

It can amplify the effects of outliers.
It can make the data less interpretable.


#Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?  Provide an example to illustrate its application.
Ans -
The unit vector technique is a feature scaling technique that rescales each feature vector to have a unit length. This is done by dividing each feature vector by its Euclidean norm. The Euclidean norm is the length of the feature vector, which is calculated by taking the square root of the sum of the squares of all of the feature values.

Unit vector scaling is different from Min-Max scaling in a few ways. First, unit vector scaling does not transform the data to a specific range, like 0 to 1. Instead, it simply ensures that each feature vector has a unit length. This means that the values of the features can still be in a wide range, but they will all be on the same scale.

Second, unit vector scaling is less sensitive to outliers than Min-Max scaling. This is because outliers can have a large impact on the range of the data, which can distort the results of Min-Max scaling. Unit vector scaling is not affected by outliers, because it only considers the length of the feature vector, not the values of the individual features.

To illustrate the application of unit vector scaling, consider the following dataset of house prices:

Feature | Value
------- | --------
Sq. ft. | 1000
Bedrooms | 3
Bathrooms | 2
Price | \$500,000
The Euclidean norm of the first feature vector is calculated as follows:

Euclidean norm = sqrt(1000^2 + 3^2 + 2^2) = 100.5
The first feature vector would then be divided by its Euclidean norm, giving us the following:

Feature | Value
------- | --------
Sq. ft. | 0.1
Bedrooms | 0.03
Bathrooms | 0.02
Price | 0.5
We would repeat this process for the Bedrooms and Price features.

After unit vector scaling, all of the feature vectors have a unit length. This makes them more comparable to each other, and it can help to improve the performance of machine learning algorithms that are sensitive to the scale of the features.

Here are some of the advantages of using unit vector scaling:

It is less sensitive to outliers than Min-Max scaling.
It can help to improve the performance of machine learning algorithms that are sensitive to the scale of the features.
Here are some of the disadvantages of using unit vector scaling:

It does not transform the data to a specific range, which can make it difficult to interpret the results.
It can be more computationally expensive than Min-Max scaling.

#Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature  Extraction? Provide an example to illustrate this concept.
Ans -

Principal component analysis (PCA) is a statistical technique that is used to reduce the dimensionality of a dataset while retaining as much information as possible. It does this by finding the directions of maximum variance in the data and projecting the data onto these directions.

PCA can be used for a variety of purposes, including:

Dimensionality reduction: PCA can be used to reduce the number of features in a dataset without losing too much information. This can be useful for machine learning algorithms that are not able to handle high-dimensional data.
Feature extraction: PCA can be used to extract the most important features from a dataset. This can be useful for tasks such as data visualization and clustering.
Noise reduction: PCA can be used to remove noise from a dataset. This can be useful for tasks such as image processing and signal processing.
To illustrate the application of PCA, consider the following dataset of house prices:

Feature | Value
------- | --------
Sq. ft. | 1000
Bedrooms | 3
Bathrooms | 2
Price | \$500,000
This dataset has 3 features: Sq. ft., Bedrooms, and Bathrooms. We can use PCA to reduce the dimensionality of this dataset to 2 dimensions. PCA would first find the directions of maximum variance in the data. In this case, the two directions of maximum variance are the Sq. ft. and Bedrooms features. PCA would then project the data onto these two directions, giving us a new dataset with 2 features.

The new dataset would still contain most of the information in the original dataset. However, it would be much easier to visualize and analyze.

Here are some of the advantages of using PCA:

It is a non-parametric technique, which means that it does not make any assumptions about the distribution of the data.
It is relatively easy to understand and implement.
It can be used with any type of data.
Here are some of the disadvantages of using PCA:

It can lose some information in the process of dimensionality reduction.
It can be sensitive to outliers.

#Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset  contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to  preprocess the data.
Ans -


In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load the training data
training_data = np.array([
    [10, 4, 3],
    [20, 5, 5],
    [30, 2, 1],
])

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the MinMaxScaler object to the training data
scaler.fit(training_data)

# Transform the training data
scaled_training_data = scaler.transform(training_data)

# Load the test data
test_data = np.array([
    [40, 1, 2],
    [50, 3, 4],
    [60, 0, 0],
])

# Transform the test data
scaled_test_data = scaler.transform(test_data)

print(scaled_training_data)
print(scaled_test_data)



[[0.         0.66666667 0.5       ]
 [0.5        1.         1.        ]
 [1.         0.         0.        ]]
[[ 1.5        -0.33333333  0.25      ]
 [ 2.          0.33333333  0.75      ]
 [ 2.5        -0.66666667 -0.25      ]]


#Q6. You are working on a project to build a model to predict stock prices. The dataset contains many  features, such as company financial data and market trends. Explain how you would use PCA to reduce the  dimensionality of the dataset.

In [5]:
import numpy as np
from sklearn.decomposition import PCA

# Load the training data
training_data = np.array([
    [10, 4, 3],
    [20, 5, 5],
    [30, 2, 1],
])

# Create a PCA object
pca = PCA()

# Fit the PCA object to the training data
pca.fit(training_data)

# Select the number of principal components to keep
n_components = 2

# Transform the training data using the PCA object
scaled_training_data = pca.transform(training_data)

# Transform the test data using the PCA object
scaled_test_data = pca.transform(test_data)
import numpy as np
from sklearn.decomposition import PCA

# Load the training data
training_data = np.array([
    [170, 70, 25, 1, 120],
    [160, 60, 30, 0, 110],
    [150, 50, 40, 1, 100],
])

# Create a PCA object
pca = PCA()

# Fit the PCA object to the training data
pca.fit(training_data)

# Calculate the cumulative explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Select the number of principal components to keep
n_components = 2

print(scaled_test_data)


[[-9.92712861e+00 -1.25029143e+00  6.76096896e-17]
 [-3.44386144e-01  2.37890226e+00  2.22044605e-16]
 [ 1.02715148e+01 -1.12861083e+00  2.22044605e-16]]
[[20.16285535  0.58356851 -1.10897395]
 [29.64329402  4.75843461 -0.27724349]
 [40.25919492  1.25092152 -0.27724349]]


#Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the  values to a range of -1 to 1.
Ans -
Here are the steps on how to perform Min-Max scaling to transform the values to a range of -1 to 1:

Find the minimum and maximum values of the data:
min_value = 1
max_value = 20
Subtract the minimum value from all of the values:
scaled_data = data - min_value
Divide all of the values by the range of the data:
scaled_data = scaled_data / (max_value - min_value)
Multiply all of the values by 2:
scaled_data = scaled_data * 2
Add 1 to all of the values:
scaled_data = scaled_data + 1
The resulting scaled data will be in the range of -1 to 1.

Here is an example:

data = [1, 5, 10, 15, 20]

min_value = min(data)
max_value = max(data)

scaled_data = (data - min_value) / (max_value - min_value)
scaled_data = scaled_data * 2
scaled_data = scaled_data + 1

print(scaled_data)
[-1.  0.  1.  2.  3. ]
The output shows the scaled data, which is now in the range of -1 to 1.

#Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform  Feature Extraction using PCA. How many principal components would you choose to retain, and why?
Ans -


In [7]:
import numpy as np
from sklearn.decomposition import PCA

# Load the training data
training_data = np.array([
    [170, 70, 25, 1, 120],
    [160, 60, 30, 0, 110],
    [150, 50, 40, 1, 100],
])

# Create a PCA object
pca = PCA()

# Fit the PCA object to the training data
pca.fit(training_data)

# Calculate the cumulative explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Select the number of principal components to keep
n_components = 2

import numpy as np
from sklearn.decomposition import PCA

# Load the training data
training_data = np.array([
    [170, 70, 25, 1, 120],
    [160, 60, 30, 0, 110],
    [150, 50, 40, 1, 100],
])

# Create a PCA object
pca = PCA()

# Fit the PCA object to the training data
pca.fit(training_data)

# Calculate the cumulative explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Select the number of principal components to keep
n_components = 2

print(scaled_test_data)

[[20.16285535  0.58356851 -1.10897395]
 [29.64329402  4.75843461 -0.27724349]
 [40.25919492  1.25092152 -0.27724349]]
